# Generated by Django 4.0.4 on 2022-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('emall', models.EmailField(max_length=254)),
                ('massig', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
