# Generated by Django 4.0.4 on 2022-05-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
