# Generated by Django 4.0.4 on 2022-05-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frst_name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_username', models.CharField(max_length=30, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('massig', models.TextField(max_length=100, verbose_name='text')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
