# Generated by Django 4.0.4 on 2022-05-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_contact_email_alter_contact_frst_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='massig',
        ),
    ]
