# Generated by Django 4.0.4 on 2022-05-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
