# Generated by Django 4.0.4 on 2022-05-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_contact_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
