# Generated by Django 4.0.4 on 2022-05-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_coment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
