# Generated by Django 4.0.4 on 2022-05-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_coment_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
