# Generated by Django 4.0.4 on 2022-05-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('massage', models.TextField()),
            ],
        ),
    ]
